The goal:
We have two data sets, one on feature charachteristics of specific individuals and the other on match outcomes of games played between said indiviuals. The goal of this exercise is to (1) build a model that can predict the outcome of an unplayed game based solely on the features of two players, especially players that are not represented in the train-test data set and, using the feature weights learnt, (2) build a ranking system of strength and recommender model that will pair a new player with the most similarly strengthed player.

Assume that the only data available is the "player_data.csv" and "match_data_classification.csv"

First we will explore our player data to understand how many players's data we have access to, the features that are present, and what these look like.

In [1]:
#Importing the required libraries
import pandas as pd
import os
#Defining the location of the CSV
DIR = '/Users/mohamed.alzarai/Desktop/Git/badminton_lads/Data Files (CSV)'
file_path = os.path.join(DIR,'player_data.csv')
#Loading data into the data frame
player_data = pd.read_csv(file_path)

#Understanding the first few data points
player_data.head()

,Unnamed: 0,Name,Height,Weight,Age,Experience,Dominant_hand,Gender,Historic Win Ratio,Reaction Time,Play Frequency,Athleticism,Serve Speed,Court Coverage,Vision
0,0,A0,180,57,18,9,left,male,0.139547,161.497106,0.740670,5,111.738777,18.438436,20/20
1,1,A1,145,63,25,17,left,male,0.716022,520.794984,0.419526,4,121.785314,26.188609,20/20
2,2,A2,188,60,31,11,right,male,0.215322,558.096477,0.102219,4,111.934328,26.949887,20/60
3,3,A3,142,79,35,4,right,male,0.552045,597.642799,0.618524,7,117.232701,13.845772,20/20
4,4,A4,142,92,25,10,left,male,0.866485,328.075735,0.453416,7,117.296644,17.403619,20/40

In [2]:
#The first column is not adding anything to our analysis as it acts as a counter, hence we can drop it
player_data.drop(player_data.columns[0], axis=1, inplace=True)
#Wanting to have a statistical view each numerical column (feature)
player_data.describe()

,Height,Weight,Age,Experience,Historic Win Ratio,Reaction Time,Play Frequency,Athleticism,Serve Speed,Court Coverage
count,182.000000,182.000000,182.000000,182.000000,182.000000,182.000000,182.000000,182.000000,182.000000,182.000000
mean,165.357143,73.115385,27.802198,10.659341,0.490782,400.350705,0.506425,4.307692,120.177428,19.756681
std,14.828632,13.247866,5.568697,5.802876,0.298619,172.347000,0.283089,1.930805,5.638640,5.770606
min,140.000000,50.000000,18.000000,1.000000,0.012662,100.243564,0.001574,1.000000,110.282967,10.154598
25%,152.000000,62.250000,23.000000,6.000000,0.240799,269.789081,0.284990,3.000000,115.491698,14.952275
50%,166.500000,73.000000,29.000000,11.000000,0.501245,394.786956,0.495564,4.000000,119.759113,19.228086
75%,178.750000,84.000000,32.000000,16.000000,0.736762,554.923613,0.741458,6.000000,125.392476,24.653415
max,190.000000,95.000000,37.000000,20.000000,0.998123,690.361614,0.994525,7.000000,129.998157,29.845143

In [3]:
player_data.corr(numeric_only=True)

,Height,Weight,Age,Experience,Historic Win Ratio,Reaction Time,Play Frequency,Athleticism,Serve Speed,Court Coverage
Height,1.000000,0.131155,-0.049253,-0.020537,-0.065737,0.003520,-0.022235,-0.085677,0.082378,0.022573
Weight,0.131155,1.000000,-0.119812,-0.078396,0.097178,0.021512,0.047485,0.091481,0.043297,-0.054612
Age,-0.049253,-0.119812,1.000000,-0.013210,-0.068872,-0.006012,-0.049600,0.064784,0.049002,-0.026268
Experience,-0.020537,-0.078396,-0.013210,1.000000,0.060884,0.043153,0.122126,0.066114,-0.005474,-0.062192
Historic Win Ratio,-0.065737,0.097178,-0.068872,0.060884,1.000000,-0.122613,0.046380,0.048026,0.008650,0.095268
Reaction Time,0.003520,0.021512,-0.006012,0.043153,-0.122613,1.000000,0.039342,0.064500,0.058287,0.085051
Play Frequency,-0.022235,0.047485,-0.049600,0.122126,0.046380,0.039342,1.000000,0.109298,-0.042244,-0.072832
Athleticism,-0.085677,0.091481,0.064784,0.066114,0.048026,0.064500,0.109298,1.000000,-0.019526,0.015879
Serve Speed,0.082378,0.043297,0.049002,-0.005474,0.008650,0.058287,-0.042244,-0.019526,1.000000,0.076611
Court Coverage,0.022573,-0.054612,-0.026268,-0.062192,0.095268,0.085051,-0.072832,0.015879,0.076611,1.000000

y§asdzz